title: "Rimsky Blog"
description: "プログラミング・開発・技術学習の記録を発信する技術ブログ"
url: "https://srinivasarimskyyamatov.github.io/blog"
lang: ja

theme: minima

minima:
  skin: dark

header_pages:
  - about.md
  - link.md
  - bg.md

plugins:
  - jekyll-sitemap

google_site_verification: ""
